<?xml version="1.0"?>
<package>
  <name>gimbalrotor</name>
  <version>1.3.2</version>
  <description>The gimbalrotor package</description>

  <maintainer email="chou@jsk.imi.i.u-tokyo.ac.jp">Bakui Chou</maintainer>
  <license>BSD</license>
  <url type="website">https://github.com/jsk-ros-pkg/jsk_aerial_robot</url>
  <author email="j-sugihara@jsk.imi.i.u-tokyo.ac.jp">Junichiro Sugihara</author>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>aerial_robot_control</build_depend>
  <build_depend>aerial_robot_estimation</build_depend>
  <build_depend>aerial_robot_model</build_depend>
  <build_depend>aerial_robot_msgs</build_depend>
  <build_depend>spinal</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>pluginlib</build_depend>
  <build_depend>controller_manager</build_depend>
  <build_depend>hardware_interface</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>catkin_virtualenv</build_depend>

  <run_depend>aerial_robot_control</run_depend>
  <run_depend>aerial_robot_estimation</run_depend>
  <run_depend>aerial_robot_model</run_depend>
  <run_depend>aerial_robot_msgs</run_depend>
  <run_depend>aerial_robot_simulation</run_depend>
  <run_depend>aerial_robot_base</run_depend>
  <run_depend>gazebo_msgs</run_depend>
  <run_depend>realsense2_camera</run_depend>
  <run_depend>gazebo_ros</run_depend>
  <run_depend>spinal</run_depend>
  <run_depend>roscpp</run_depend>
  <run_depend>pluginlib</run_depend>
  <run_depend>controller_manager</run_depend>
  <run_depend>hardware_interface</run_depend>
  <run_depend>joint_trajectory_controller</run_depend>
  <run_depend>position_controllers</run_depend>
  <run_depend>sensor_msgs</run_depend>
  <run_depend>controller_manager_msgs</run_depend>
  <run_depend>rospy</run_depend>
  <run_depend>std_msgs</run_depend>
  <run_depend>control_msgs</run_depend>
  <run_depend>actionlib</run_depend>
  <run_depend>std_srvs</run_depend>
  <run_depend>trajectory_msgs</run_depend>
  <!-- scikit-robot is installed into the package virtualenv by catkin_virtualenv (requirements.in) -->

  <test_depend>rostest</test_depend>

  <export>
    <aerial_robot_model plugin="${prefix}/plugins/robot_model_plugins.xml" />
    <aerial_robot_control plugin="${prefix}/plugins/control_plugins.xml" />
    <aerial_robot_control plugin="${prefix}/plugins/navigation_plugin.xml" />
    <pip_requirements>requirements.txt</pip_requirements>
    <gazebo_ros gazebo_model_path="${prefix}/models" />
  </export>

</package>
